import Sidebar from '@/components/general/nav/sidebar/SideBar';
import Header from '@/components/general/nav/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <div>
      <div className="grid grid-rows-[auto_1fr]">
        <Header />
        <main className="grid grid-cols-[auto_1fr]">
          <Sidebar />
          <div className="mx-auto h-[calc(100vh-64px)] w-full max-w-7xl overflow-y-auto p-6 pb-24">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
}
