export const workoutsMockData = [
  {
    id: 1,
    nombre: 'Sentadillas',
    categoria: 'Fuerza',
    duracion: '3 series de 15 repeticiones',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/aclHkVaku9U',
    explicacion:
      'Las sentadillas son un ejercicio fundamental para fortalecer las piernas y glúteos. Este movimiento compuesto trabaja múltiples grupos musculares simultáneamente.',
    instrucciones: [
      'Párate con los pies al ancho de los hombros',
      'Mantén la espalda recta y el pecho hacia arriba',
      'Baja lentamente doblando las rodillas',
      'Desciende hasta que tus muslos estén paralelos al suelo',
      'Empuja con los talones para volver a la posición inicial',
    ],
    beneficios: [
      'Fortalece cuádriceps, glúteos e isquiotibiales',
      'Mejora la movilidad de cadera',
      'Aumenta la fuerza del core',
      'Quema calorías efectivamente',
    ],
    precauciones: [
      'No dejes que las rodillas sobrepasen los dedos de los pies',
      'Mantén siempre la espalda recta',
      'Si tienes problemas de rodilla, consulta antes de realizar',
    ],
  },
  {
    id: 2,
    nombre: 'Plancha Abdominal',
    categoria: 'Core',
    duracion: '3 series de 30 segundos',
    nivel: 'Principiante',
    imagenPrincipal: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/pSHjTRCQxIw',
    explicacion:
      'La plancha es un ejercicio isométrico excelente para fortalecer todo el core, incluyendo abdominales, espalda baja y hombros.',
    instrucciones: [
      'Colócate en posición de flexión sobre los antebrazos',
      'Mantén el cuerpo en línea recta desde la cabeza hasta los talones',
      'Contrae el abdomen y glúteos',
      'Mantén la posición sin dejar caer las caderas',
      'Respira de manera constante',
    ],
    beneficios: [
      'Fortalece el core completo',
      'Mejora la postura',
      'Reduce el dolor de espalda',
      'Aumenta la estabilidad',
    ],
    precauciones: [
      'No arquees la espalda',
      'Mantén el cuello en posición neutral',
      'Si sientes dolor en la espalda baja, detente',
    ],
  },
  {
    id: 3,
    nombre: 'Burpees',
    categoria: 'Cardio',
    duracion: '3 series de 10 repeticiones',
    nivel: 'Avanzado',
    imagenPrincipal: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/dZgVxmf6jkA',
    explicacion:
      'Los burpees son un ejercicio de cuerpo completo que combina fuerza y cardio, ideal para quemar calorías y mejorar la resistencia.',
    instrucciones: [
      'Comienza de pie',
      'Baja a posición de cuclillas y coloca las manos en el suelo',
      'Salta con los pies hacia atrás a posición de plancha',
      'Realiza una flexión (opcional)',
      'Salta con los pies hacia adelante',
      'Salta verticalmente con los brazos arriba',
    ],
    beneficios: [
      'Ejercicio de cuerpo completo',
      'Quema muchas calorías',
      'Mejora la resistencia cardiovascular',
      'Aumenta la fuerza funcional',
    ],
    precauciones: [
      'Calienta bien antes de realizar',
      'Mantén el core contraído durante todo el movimiento',
      'Modifica si tienes problemas de muñeca o rodilla',
    ],
  },
  {
    id: 4,
    nombre: 'Estiramiento de Gato-Vaca',
    categoria: 'Flexibilidad',
    duracion: '2 series de 10 repeticiones',
    nivel: 'Principiante',
    imagenPrincipal: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/kqnua4rHVVA',
    explicacion:
      'Este estiramiento de yoga es perfecto para mejorar la flexibilidad de la columna y aliviar la tensión en la espalda.',
    instrucciones: [
      'Colócate en cuatro puntos (manos y rodillas)',
      'Arquea la espalda hacia arriba (posición de gato)',
      'Mantén 5 segundos',
      'Arquea la espalda hacia abajo (posición de vaca)',
      'Mantén 5 segundos',
      'Repite el movimiento fluidamente',
    ],
    beneficios: [
      'Mejora la flexibilidad de la columna',
      'Alivia la tensión en la espalda',
      'Masajea los órganos internos',
      'Reduce el estrés',
    ],
    precauciones: [
      'Realiza los movimientos lentamente',
      'No fuerces el rango de movimiento',
      'Respira profundamente durante el ejercicio',
    ],
  },
  {
    id: 5,
    nombre: 'Flexiones de Pecho',
    categoria: 'Fuerza',
    duracion: '3 series de 12 repeticiones',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600',
      'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/IODxDxX7oi4',
    explicacion:
      'Las flexiones son un ejercicio clásico que fortalece el pecho, hombros y tríceps utilizando el peso corporal.',
    instrucciones: [
      'Colócate en posición de plancha con las manos al ancho de los hombros',
      'Mantén el cuerpo en línea recta',
      'Baja el pecho hacia el suelo doblando los codos',
      'Desciende hasta que el pecho casi toque el suelo',
      'Empuja hacia arriba hasta extender los brazos',
    ],
    beneficios: [
      'Fortalece pectorales, hombros y tríceps',
      'Mejora la fuerza del core',
      'No requiere equipo',
      'Aumenta la resistencia muscular',
    ],
    precauciones: [
      'Mantén los codos cerca del cuerpo',
      'No dejes caer las caderas',
      'Modifica apoyando las rodillas si es necesario',
    ],
  },
  {
    id: 6,
    nombre: 'Zancadas',
    categoria: 'Fuerza',
    duracion: '3 series de 12 repeticiones por pierna',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/QOVaHwm-Q6U',
    explicacion:
      'Las zancadas son excelentes para desarrollar fuerza en las piernas de manera unilateral, mejorando también el equilibrio.',
    instrucciones: [
      'Párate con los pies al ancho de las caderas',
      'Da un paso largo hacia adelante',
      'Baja la rodilla trasera hacia el suelo',
      'Mantén la rodilla delantera alineada con el tobillo',
      'Empuja con el pie delantero para volver a la posición inicial',
    ],
    beneficios: [
      'Fortalece cuádriceps y glúteos',
      'Mejora el equilibrio y coordinación',
      'Corrige desequilibrios musculares',
      'Aumenta la flexibilidad de la cadera',
    ],
    precauciones: [
      'No dejes que la rodilla delantera sobrepase los dedos del pie',
      'Mantén el torso erguido',
      'Comienza con zancadas estáticas si eres principiante',
    ],
  },
  {
    id: 7,
    nombre: 'Mountain Climbers',
    categoria: 'Cardio',
    duracion: '3 series de 30 segundos',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600',
      'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/nmwgirgXLYM',
    explicacion:
      'Los mountain climbers son un ejercicio cardiovascular intenso que también fortalece el core y mejora la agilidad.',
    instrucciones: [
      'Comienza en posición de plancha alta',
      'Lleva una rodilla hacia el pecho',
      'Regresa la pierna a la posición inicial',
      'Alterna rápidamente las piernas',
      'Mantén las caderas bajas y estables',
    ],
    beneficios: [
      'Ejercicio cardiovascular efectivo',
      'Fortalece el core',
      'Mejora la coordinación',
      'Quema calorías rápidamente',
    ],
    precauciones: [
      'Mantén las manos firmes en el suelo',
      'No eleves demasiado las caderas',
      'Comienza lento y aumenta la velocidad gradualmente',
    ],
  },
  {
    id: 8,
    nombre: 'Abdominales Bicicleta',
    categoria: 'Core',
    duracion: '3 series de 20 repeticiones',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/9FGilxCbdz8',
    explicacion:
      'Los abdominales bicicleta son uno de los ejercicios más efectivos para trabajar los oblicuos y el core completo.',
    instrucciones: [
      'Acuéstate boca arriba con las manos detrás de la cabeza',
      'Eleva las piernas en ángulo de 90 grados',
      'Lleva el codo derecho hacia la rodilla izquierda',
      'Extiende la pierna derecha mientras rotas',
      'Alterna los lados en un movimiento de pedaleo',
    ],
    beneficios: [
      'Trabaja los oblicuos intensamente',
      'Fortalece el core completo',
      'Mejora la coordinación',
      'Define la cintura',
    ],
    precauciones: [
      'No tires del cuello con las manos',
      'Mantén la espalda baja pegada al suelo',
      'Realiza los movimientos de forma controlada',
    ],
  },
  {
    id: 9,
    nombre: 'Jumping Jacks',
    categoria: 'Cardio',
    duracion: '3 series de 30 repeticiones',
    nivel: 'Principiante',
    imagenPrincipal: 'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=600',
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/c4DAnQ6DtF8',
    explicacion:
      'Los jumping jacks son un ejercicio cardiovascular clásico, perfecto para calentamiento o entrenamiento de alta intensidad.',
    instrucciones: [
      'Párate con los pies juntos y brazos a los lados',
      'Salta abriendo las piernas al ancho de los hombros',
      'Simultáneamente eleva los brazos sobre la cabeza',
      'Salta de nuevo juntando los pies',
      'Baja los brazos a la posición inicial',
    ],
    beneficios: [
      'Excelente calentamiento cardiovascular',
      'Mejora la coordinación',
      'Aumenta la frecuencia cardíaca',
      'Ejercita todo el cuerpo',
    ],
    precauciones: [
      'Aterriza suavemente para proteger las articulaciones',
      'Mantén el core activado',
      'Modifica eliminando el salto si es necesario',
    ],
  },
  {
    id: 10,
    nombre: 'Peso Muerto',
    categoria: 'Fuerza',
    duracion: '3 series de 10 repeticiones',
    nivel: 'Avanzado',
    imagenPrincipal: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/op9kVnSso6Q',
    explicacion:
      'El peso muerto es uno de los ejercicios más completos para desarrollar fuerza en la cadena posterior del cuerpo.',
    instrucciones: [
      'Párate con los pies al ancho de las caderas',
      'Inclínate hacia adelante desde las caderas',
      'Mantén la espalda recta y el pecho hacia arriba',
      'Baja hasta sentir estiramiento en los isquiotibiales',
      'Regresa a la posición inicial apretando los glúteos',
    ],
    beneficios: [
      'Fortalece isquiotibiales, glúteos y espalda baja',
      'Mejora la postura',
      'Aumenta la fuerza funcional',
      'Previene lesiones en la espalda',
    ],
    precauciones: [
      'Mantén siempre la espalda recta',
      'No redondees la espalda baja',
      'Comienza con poco peso o sin peso',
    ],
  },
  {
    id: 11,
    nombre: 'Plancha Lateral',
    categoria: 'Core',
    duracion: '3 series de 30 segundos por lado',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/K2VljzCC16g',
    explicacion:
      'La plancha lateral es excelente para fortalecer los oblicuos y mejorar la estabilidad lateral del core.',
    instrucciones: [
      'Acuéstate de lado apoyándote en un antebrazo',
      'Apila los pies uno sobre otro',
      'Eleva las caderas formando una línea recta',
      'Mantén el core contraído',
      'Sostén la posición sin dejar caer las caderas',
    ],
    beneficios: [
      'Fortalece los oblicuos',
      'Mejora el equilibrio',
      'Reduce el riesgo de lesiones de espalda',
      'Aumenta la estabilidad del core',
    ],
    precauciones: [
      'Mantén el cuerpo alineado',
      'No dejes caer las caderas',
      'Modifica apoyando la rodilla inferior si es necesario',
    ],
  },
  {
    id: 12,
    nombre: 'Estiramiento de Isquiotibiales',
    categoria: 'Flexibilidad',
    duracion: '3 series de 30 segundos por pierna',
    nivel: 'Principiante',
    imagenPrincipal: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/3B-3Dc6yLzk',
    explicacion:
      'Este estiramiento es fundamental para mantener la flexibilidad de las piernas y prevenir lesiones.',
    instrucciones: [
      'Siéntate en el suelo con las piernas extendidas',
      'Mantén la espalda recta',
      'Inclínate hacia adelante desde las caderas',
      'Alcanza los pies con las manos',
      'Mantén el estiramiento sin rebotar',
    ],
    beneficios: [
      'Mejora la flexibilidad de isquiotibiales',
      'Reduce la tensión en la espalda baja',
      'Previene lesiones musculares',
      'Mejora el rango de movimiento',
    ],
    precauciones: [
      'No redondees la espalda',
      'Respira profundamente durante el estiramiento',
      'No rebotes ni fuerces el movimiento',
    ],
  },
  {
    id: 13,
    nombre: 'Fondos de Tríceps',
    categoria: 'Fuerza',
    duracion: '3 series de 12 repeticiones',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600',
      'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/6kALZikXxLc',
    explicacion:
      'Los fondos de tríceps son perfectos para fortalecer la parte posterior de los brazos usando una silla o banco.',
    instrucciones: [
      'Siéntate en el borde de una silla o banco',
      'Coloca las manos al lado de las caderas',
      'Desliza las caderas fuera del asiento',
      'Baja el cuerpo doblando los codos a 90 grados',
      'Empuja hacia arriba extendiendo los brazos',
    ],
    beneficios: [
      'Fortalece los tríceps intensamente',
      'Trabaja los hombros y pecho',
      'Requiere equipo mínimo',
      'Mejora la fuerza de empuje',
    ],
    precauciones: [
      'Mantén los codos apuntando hacia atrás',
      'No bajes demasiado si sientes dolor en los hombros',
      'Mantén los hombros alejados de las orejas',
    ],
  },
  {
    id: 14,
    nombre: 'Elevación de Piernas',
    categoria: 'Core',
    duracion: '3 series de 15 repeticiones',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/JB2oyawG9KI',
    explicacion:
      'Las elevaciones de piernas son excelentes para trabajar la parte inferior del abdomen y el core completo.',
    instrucciones: [
      'Acuéstate boca arriba con las piernas extendidas',
      'Coloca las manos bajo los glúteos para soporte',
      'Eleva las piernas manteniendo las rodillas rectas',
      'Sube hasta formar un ángulo de 90 grados',
      'Baja lentamente sin tocar el suelo',
    ],
    beneficios: [
      'Fortalece el abdomen inferior',
      'Mejora la fuerza del core',
      'Aumenta la estabilidad lumbar',
      'Define los abdominales',
    ],
    precauciones: [
      'Mantén la espalda baja pegada al suelo',
      'No uses impulso para subir las piernas',
      'Dobla ligeramente las rodillas si es necesario',
    ],
  },
  {
    id: 15,
    nombre: 'Saltos con Sentadilla',
    categoria: 'Cardio',
    duracion: '3 series de 15 repeticiones',
    nivel: 'Avanzado',
    imagenPrincipal: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600',
      'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/CVaEhXotL7M',
    explicacion:
      'Los saltos con sentadilla combinan fuerza de piernas con ejercicio cardiovascular de alta intensidad.',
    instrucciones: [
      'Comienza en posición de sentadilla',
      'Baja hasta que los muslos estén paralelos al suelo',
      'Explota hacia arriba con un salto potente',
      'Extiende completamente las piernas en el aire',
      'Aterriza suavemente y vuelve a la sentadilla',
    ],
    beneficios: [
      'Desarrolla potencia explosiva',
      'Quema calorías intensamente',
      'Fortalece piernas y glúteos',
      'Mejora la capacidad atlética',
    ],
    precauciones: [
      'Aterriza con las rodillas ligeramente flexionadas',
      'Calienta bien antes de realizar',
      'Evita si tienes problemas de rodilla',
    ],
  },
  {
    id: 16,
    nombre: 'Perro Boca Abajo',
    categoria: 'Flexibilidad',
    duracion: '3 series de 30 segundos',
    nivel: 'Principiante',
    imagenPrincipal: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/pvEGjNV_XuQ',
    explicacion:
      'Esta postura de yoga clásica estira todo el cuerpo mientras fortalece brazos y hombros.',
    instrucciones: [
      'Comienza en cuatro puntos',
      'Levanta las caderas hacia el techo',
      'Forma una V invertida con el cuerpo',
      'Presiona los talones hacia el suelo',
      'Mantén los brazos y piernas extendidos',
    ],
    beneficios: [
      'Estira toda la cadena posterior',
      'Fortalece brazos y hombros',
      'Alivia el estrés',
      'Mejora la circulación',
    ],
    precauciones: [
      'No fuerces los talones al suelo',
      'Mantén las orejas entre los brazos',
      'Modifica doblando ligeramente las rodillas si es necesario',
    ],
  },
  {
    id: 17,
    nombre: 'Press de Hombros',
    categoria: 'Fuerza',
    duracion: '3 series de 12 repeticiones',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
      'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/qEwKCR5JCog',
    explicacion:
      'El press de hombros es fundamental para desarrollar fuerza y masa muscular en los hombros.',
    instrucciones: [
      'Párate con los pies al ancho de los hombros',
      'Sostén pesos a la altura de los hombros',
      'Presiona los pesos hacia arriba sobre la cabeza',
      'Extiende completamente los brazos',
      'Baja controladamente a la posición inicial',
    ],
    beneficios: [
      'Desarrolla los hombros',
      'Fortalece el core',
      'Mejora la postura',
      'Aumenta la fuerza de empuje',
    ],
    precauciones: [
      'No arquees la espalda baja',
      'Mantén el core contraído',
      'Comienza con poco peso',
    ],
  },
  {
    id: 18,
    nombre: 'High Knees',
    categoria: 'Cardio',
    duracion: '3 series de 30 segundos',
    nivel: 'Intermedio',
    imagenPrincipal: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600',
      'https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/8opcQdC-V-U',
    explicacion:
      'Los high knees son un ejercicio cardiovascular intenso que mejora la coordinación y quema calorías.',
    instrucciones: [
      'Párate con los pies al ancho de las caderas',
      'Corre en el lugar elevando las rodillas al pecho',
      'Mantén un ritmo rápido',
      'Balancea los brazos naturalmente',
      'Aterriza en la parte delantera de los pies',
    ],
    beneficios: [
      'Excelente ejercicio cardiovascular',
      'Mejora la coordinación',
      'Fortalece el core',
      'Quema calorías rápidamente',
    ],
    precauciones: [
      'Calienta antes de comenzar',
      'Mantén el torso erguido',
      'Aterriza suavemente para proteger las articulaciones',
    ],
  },
  {
    id: 19,
    nombre: 'Crunches Abdominales',
    categoria: 'Core',
    duracion: '3 series de 20 repeticiones',
    nivel: 'Principiante',
    imagenPrincipal: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/Xyd_fa5zoEU',
    explicacion:
      'Los crunches son el ejercicio clásico para fortalecer los abdominales superiores de manera efectiva.',
    instrucciones: [
      'Acuéstate boca arriba con las rodillas dobladas',
      'Coloca las manos detrás de la cabeza',
      'Contrae el abdomen y eleva los hombros del suelo',
      'Exhala al subir',
      'Baja lentamente sin relajar completamente',
    ],
    beneficios: [
      'Fortalece los abdominales superiores',
      'Ejercicio básico y efectivo',
      'No requiere equipo',
      'Fácil de modificar',
    ],
    precauciones: [
      'No tires del cuello',
      'Mantén la barbilla separada del pecho',
      'Evita usar impulso',
    ],
  },
  {
    id: 20,
    nombre: 'Estiramiento de Cuádriceps',
    categoria: 'Flexibilidad',
    duracion: '3 series de 30 segundos por pierna',
    nivel: 'Principiante',
    imagenPrincipal: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    imagenes: [
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
    ],
    videoUrl: 'https://www.youtube.com/embed/ENoXNjBYZJI',
    explicacion:
      'Este estiramiento es esencial para mantener la flexibilidad de los cuádriceps y prevenir lesiones.',
    instrucciones: [
      'Párate sobre una pierna',
      'Dobla la otra rodilla llevando el talón hacia el glúteo',
      'Agarra el tobillo con la mano',
      'Mantén las rodillas juntas',
      'Empuja ligeramente la cadera hacia adelante',
    ],
    beneficios: [
      'Mejora la flexibilidad de los cuádriceps',
      'Reduce la tensión en las rodillas',
      'Mejora el equilibrio',
      'Previene lesiones musculares',
    ],
    precauciones: [
      'Mantén el equilibrio apoyándote si es necesario',
      'No fuerces la rodilla',
      'Mantén las caderas alineadas',
    ],
  },
];

export const categorias = ['Todos', 'Fuerza', 'Cardio', 'Core', 'Flexibilidad'];
