export const diets = [
  {
    id: 1,
    nombre: 'Plan Mediterráneo',
    descripcion: 'Dieta balanceada rica en vegetales y pescado',
    duracion: '30 días',
    medico: 'Dra. Johana Lemus',
  },
  {
    id: 2,
    nombre: 'Plan Bajo en Carbohidratos',
    descripcion: 'Reducción gradual de carbohidratos para mejorar metabolismo',
    duracion: '45 días',
    medico: 'Dr. Arturo Lemus',
  },
  {
    id: 3,
    nombre: 'Plan Vegetariano',
    descripcion: 'Alimentación basada en plantas con fuentes proteicas vegetales',
    duracion: '60 días',
    medico: 'Dra. Maureen Acosta',
  },
  {
    id: 4,
    nombre: 'Plan Detox Verde',
    descripcion: 'Desintoxicación con jugos naturales y vegetales verdes',
    duracion: '7 días',
    medico: 'Dra. Fernanda Ruiz',
  },
  {
    id: 5,
    nombre: 'Plan Proteico',
    descripcion: 'Alta en proteínas magras para conservar masa muscular',
    duracion: '30 días',
    medico: 'Dr. Eduardo Torres',
  },
  {
    id: 6,
    nombre: 'Plan Keto',
    descripcion: 'Plan cetogénico con reducción drástica de carbohidratos',
    duracion: '21 días',
    medico: 'Dra. Gabriela Soto',
  },
  {
    id: 7,
    nombre: 'Plan DASH',
    descripcion: 'Diseñado para controlar la presión arterial y el colesterol',
    duracion: '60 días',
    medico: 'Dr. Nicolás Castro',
  },
  {
    id: 8,
    nombre: 'Plan Antiinflamatorio',
    descripcion: 'Rico en antioxidantes y grasas saludables',
    duracion: '30 días',
    medico: 'Dra. Karla Domínguez',
  },
  {
    id: 9,
    nombre: 'Plan Paleo',
    descripcion: 'Basado en alimentos naturales no procesados',
    duracion: '40 días',
    medico: 'Dr. Mauricio Ortega',
  },
  {
    id: 10,
    nombre: 'Plan Hipocalórico',
    descripcion: 'Control calórico para pérdida de peso progresiva',
    duracion: '50 días',
    medico: 'Dra. Cristina Ramos',
  },
  {
    id: 11,
    nombre: 'Plan Anticolesterol',
    descripcion: 'Reducción de grasas saturadas y aumento de fibra',
    duracion: '30 días',
    medico: 'Dr. Alejandro Gómez',
  },
  {
    id: 12,
    nombre: 'Plan Sin Gluten',
    descripcion: 'Eliminación total de gluten y harinas refinadas',
    duracion: '45 días',
    medico: 'Dra. Patricia Serrano',
  },
  {
    id: 13,
    nombre: 'Plan Detox Frutal',
    descripcion: 'Basado en frutas frescas y agua de coco',
    duracion: '5 días',
    medico: 'Dra. Johana Lemus',
  },
  {
    id: 14,
    nombre: 'Plan Vegano',
    descripcion: 'Alimentación 100% vegetal con suplementos esenciales',
    duracion: '60 días',
    medico: 'Dr. Arturo Lemus',
  },
  {
    id: 15,
    nombre: 'Plan Intermitente 16:8',
    descripcion: 'Ayuno intermitente con ventana alimenticia de 8 horas',
    duracion: '21 días',
    medico: 'Dra. Maureen Acosta',
  },
  {
    id: 16,
    nombre: 'Plan Balance Hormonal',
    descripcion: 'Diseñado para mejorar el equilibrio hormonal femenino',
    duracion: '30 días',
    medico: 'Dra. Fernanda Ruiz',
  },
  {
    id: 17,
    nombre: 'Plan Deportivo',
    descripcion: 'Optimización del rendimiento físico y recuperación muscular',
    duracion: '45 días',
    medico: 'Dr. Eduardo Torres',
  },
  {
    id: 18,
    nombre: 'Plan Control de Azúcar',
    descripcion: 'Reducción de azúcares simples y mejora de la sensibilidad a la insulina',
    duracion: '60 días',
    medico: 'Dra. Gabriela Soto',
  },
  {
    id: 19,
    nombre: 'Plan Hipertensión',
    descripcion: 'Reducción de sodio y aumento de potasio y magnesio',
    duracion: '40 días',
    medico: 'Dr. Nicolás Castro',
  },
  {
    id: 20,
    nombre: 'Plan Salud Digestiva',
    descripcion: 'Mejora del tránsito intestinal con probióticos y fibra',
    duracion: '30 días',
    medico: 'Dra. Karla Domínguez',
  },
];
